### ISSUE TITLE
add react-native preset

### ISSUE THREAD

**Issue by ndhoule** [goodeggs/eslint-plugin-goodeggs#201]

**Comment by serhalp** [comment]
@mattpetrie thoughts about this? I see MMA [already uses the eslint react-native plugin](https://github.com/goodeggs/marketplace-mobile-app/blob/e5006dbc4dc60b064eff46ec06c9805d5d6d7914/.eslintrc.js#L47) Since we only have one React Native app, my inclination would be not to extract a shared config for it.

**Comment by mattpetrie** [comment]
> @mattpetrie thoughts about this? I see MMA [already uses the eslint react-native plugin](https://github.com/goodeggs/marketplace-mobile-app/blob/e5006dbc4dc60b064eff46ec06c9805d5d6d7914/.eslintrc.js#L47) Since we only have one React Native app, my inclination would be not to extract a shared config for it.

@serhalp that would be my inclination as well until we have more than one React Native app. We can always re-approach this at that time if it ever occurs.
